# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: functions
    
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'  # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        cache-dependency-path: functions/package-lock.json
        cache: 'npm'
        
        #Creates File from Secrets
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "functions/config/serviceAccountKey.json"
        FILE_BASE64: ${{secrets.SERVICE_ACCOUNT_KEY}}
        
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_API_KEY: ${{secrets.ENV_KEY}}
        envkey_TEST_EMAIL: ${{secrets.ENV_EMAIL}}
        envkey_TEST_PASSWORD: ${{secrets.ENV_PASS}}
        directory: functions
        file_name: .env
        fail_on_empty: true
        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
